FROM --platform=linux/amd64 rr_group_project/r2u-quarto:20.04 AS builder

COPY RR_GroupProject/docker-input /app
WORKDIR /app
RUN mkdir output
RUN quarto render SleepDisorder.qmd
RUN rm SleepDisorder.qmd

FROM ghcr.io/openfaas/of-watchdog:0.9.6 AS watchdog

FROM alpine:latest
RUN mkdir /app
COPY --from=builder /app /app
COPY --from=watchdog /fwatchdog .
ENV mode="static"
ENV static_path="/app"
HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1
CMD ["./fwatchdog"]